-- LibCore schema completo para PostgreSQL
-- Conversão a partir do schema MySQL original.
-- Não inclui CREATE DATABASE.

-- Remova as tabelas em ordem de dependência.
DROP TABLE IF EXISTS auditoria CASCADE;
DROP TABLE IF EXISTS multas CASCADE;
DROP TABLE IF EXISTS notificacoes CASCADE;
DROP TABLE IF EXISTS reservas CASCADE;
DROP TABLE IF EXISTS salas CASCADE;
DROP TABLE IF EXISTS espacos CASCADE;
DROP TABLE IF EXISTS emprestimos CASCADE;
DROP TABLE IF EXISTS transacoes CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS livros CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS localizacao_livro CASCADE;

-- Remova os tipos ENUM, caso já existam.
DROP TYPE IF EXISTS tipo_usuario_enum CASCADE;
DROP TYPE IF EXISTS status_livro_enum CASCADE;
DROP TYPE IF EXISTS status_ticket_enum CASCADE;
DROP TYPE IF EXISTS tipo_transacao_enum CASCADE;
DROP TYPE IF EXISTS status_emprestimo_enum CASCADE;
DROP TYPE IF EXISTS tipo_espaco_enum CASCADE;
DROP TYPE IF EXISTS status_sala_enum CASCADE;
DROP TYPE IF EXISTS status_reserva_enum CASCADE;
DROP TYPE IF EXISTS tipo_notificacao_enum CASCADE;
DROP TYPE IF EXISTS status_multa_enum CASCADE;

-- Tipos ENUM equivalentes aos ENUMs do MySQL.
CREATE TYPE tipo_usuario_enum AS ENUM ('LEITOR', 'BIBLIOTECARIO', 'ADMIN', 'TOTEM');
CREATE TYPE status_livro_enum AS ENUM ('DISPONIVEL', 'EMPRESTADO', 'RESERVADO', 'MANUTENCAO', 'INDISPONIVEL');
CREATE TYPE status_ticket_enum AS ENUM ('ABERTO', 'EM_ANDAMENTO', 'FINALIZADO', 'CANCELADO');
CREATE TYPE tipo_transacao_enum AS ENUM ('EMPRESTIMO', 'DEVOLUCAO', 'RENOVACAO', 'RESERVA');
CREATE TYPE status_emprestimo_enum AS ENUM ('ATIVO', 'DEVOLVIDO', 'ATRASADO', 'CANCELADO');
CREATE TYPE tipo_espaco_enum AS ENUM ('SALA_ESTUDO', 'MESA_INDIVIDUAL', 'AREA_LEITURA');
CREATE TYPE status_sala_enum AS ENUM ('ABERTA', 'FECHADA');
CREATE TYPE status_reserva_enum AS ENUM ('CONFIRMADA', 'CANCELADA', 'FINALIZADA');
CREATE TYPE tipo_notificacao_enum AS ENUM ('AVISO', 'RESERVA', 'DEVOLUCAO', 'MULTA', 'SISTEMA');
CREATE TYPE status_multa_enum AS ENUM ('ABERTA', 'PAGA', 'CANCELADA');

CREATE TABLE IF NOT EXISTS localizacao_livro (
  id_localizacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setor varchar(50) NOT NULL,
  estante varchar(20) NOT NULL,
  divisoria varchar(20) NOT NULL,
  numero integer NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_usuario varchar(150) NOT NULL,
  email_usuario varchar(150) NOT NULL UNIQUE,
  cpf_usuario char(11) NOT NULL UNIQUE,
  facial_usuario text,
  tipo_usuario tipo_usuario_enum NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  senha_hash varchar(128) DEFAULT NULL,
  senha_salt varchar(64) DEFAULT NULL,
  token_validacao char(6) DEFAULT NULL,
  token_validacao_ativo boolean NOT NULL DEFAULT false,
  token_validacao_gerado_em timestamp DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS token_validacao_idx
  ON usuarios (token_validacao, token_validacao_ativo);

CREATE TABLE IF NOT EXISTS livros (
  id_livro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etiqueta_rfid varchar(100) NOT NULL UNIQUE,
  nome_livro varchar(255) NOT NULL,
  autor_livro varchar(150) DEFAULT NULL,
  categoria_livro varchar(100) DEFAULT NULL,
  isbn_livro varchar(20) DEFAULT NULL,
  status_livro status_livro_enum NOT NULL DEFAULT 'DISPONIVEL',
  id_localizacao integer DEFAULT NULL,
  CONSTRAINT livros_ibfk_1 FOREIGN KEY (id_localizacao) REFERENCES localizacao_livro (id_localizacao)
);

CREATE INDEX IF NOT EXISTS livros_id_localizacao_idx ON livros (id_localizacao);

CREATE TABLE IF NOT EXISTS tickets (
  id_ticket integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_criacao timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_finalizacao timestamp DEFAULT NULL,
  status status_ticket_enum NOT NULL DEFAULT 'ABERTO',
  tipo varchar(50) NOT NULL,
  descricao text,
  id_usuario integer NOT NULL,
  CONSTRAINT tickets_ibfk_1 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

CREATE INDEX IF NOT EXISTS tickets_id_usuario_idx ON tickets (id_usuario);

CREATE TABLE IF NOT EXISTS transacoes (
  id_transacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo tipo_transacao_enum NOT NULL,
  data timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario integer NOT NULL,
  id_livro integer NOT NULL,
  CONSTRAINT transacoes_ibfk_1 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
  CONSTRAINT transacoes_ibfk_2 FOREIGN KEY (id_livro) REFERENCES livros (id_livro)
);

CREATE INDEX IF NOT EXISTS transacoes_id_usuario_idx ON transacoes (id_usuario);
CREATE INDEX IF NOT EXISTS transacoes_id_livro_idx ON transacoes (id_livro);

CREATE TABLE IF NOT EXISTS emprestimos (
  id_emprestimo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL,
  id_livro integer NOT NULL,
  data_emprestimo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_prevista_devolucao timestamp NOT NULL,
  data_devolucao timestamp DEFAULT NULL,
  status status_emprestimo_enum NOT NULL DEFAULT 'ATIVO',
  CONSTRAINT emprestimos_ibfk_1 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
  CONSTRAINT emprestimos_ibfk_2 FOREIGN KEY (id_livro) REFERENCES livros (id_livro)
);

CREATE INDEX IF NOT EXISTS emprestimos_id_usuario_idx ON emprestimos (id_usuario);
CREATE INDEX IF NOT EXISTS emprestimos_id_livro_idx ON emprestimos (id_livro);

CREATE TABLE IF NOT EXISTS espacos (
  id_espaco integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_espaco varchar(100) NOT NULL,
  tipo_espaco tipo_espaco_enum NOT NULL,
  capacidade integer NOT NULL
);

CREATE TABLE IF NOT EXISTS salas (
  id_sala integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_espaco integer DEFAULT NULL,
  nome_sala varchar(100) NOT NULL,
  status_sala status_sala_enum NOT NULL DEFAULT 'ABERTA',
  camera_url text DEFAULT NULL,
  largura_planta numeric(10,2) DEFAULT NULL,
  altura_planta numeric(10,2) DEFAULT NULL,
  metadata jsonb DEFAULT NULL,
  atualizada_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT salas_ibfk_1 FOREIGN KEY (id_espaco) REFERENCES espacos (id_espaco)
);

CREATE INDEX IF NOT EXISTS salas_id_espaco_idx ON salas (id_espaco);

CREATE TABLE IF NOT EXISTS reservas (
  id_reserva integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL,
  id_espaco integer NOT NULL,
  data_inicio timestamp NOT NULL,
  data_fim timestamp NOT NULL,
  status status_reserva_enum NOT NULL DEFAULT 'CONFIRMADA',
  CONSTRAINT reservas_ibfk_1 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
  CONSTRAINT reservas_ibfk_2 FOREIGN KEY (id_espaco) REFERENCES espacos (id_espaco)
);

CREATE INDEX IF NOT EXISTS reservas_id_usuario_idx ON reservas (id_usuario);
CREATE INDEX IF NOT EXISTS reservas_id_espaco_idx ON reservas (id_espaco);

CREATE TABLE IF NOT EXISTS notificacoes (
  id_notificacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL,
  tipo tipo_notificacao_enum NOT NULL,
  titulo varchar(150) NOT NULL,
  mensagem text NOT NULL,
  lida boolean NOT NULL DEFAULT false,
  data_criacao timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notificacoes_ibfk_1 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

CREATE INDEX IF NOT EXISTS notificacoes_id_usuario_idx ON notificacoes (id_usuario);

CREATE TABLE IF NOT EXISTS multas (
  id_multa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL,
  id_emprestimo integer DEFAULT NULL,
  valor numeric(10,2) NOT NULL,
  status status_multa_enum NOT NULL DEFAULT 'ABERTA',
  data_geracao timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_pagamento timestamp DEFAULT NULL,
  CONSTRAINT multas_ibfk_1 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
  CONSTRAINT multas_ibfk_2 FOREIGN KEY (id_emprestimo) REFERENCES emprestimos (id_emprestimo)
);

CREATE INDEX IF NOT EXISTS multas_id_usuario_idx ON multas (id_usuario);
CREATE INDEX IF NOT EXISTS multas_id_emprestimo_idx ON multas (id_emprestimo);

CREATE TABLE IF NOT EXISTS auditoria (
  id_auditoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer DEFAULT NULL,
  acao varchar(120) NOT NULL,
  entidade varchar(80) NOT NULL,
  id_entidade integer DEFAULT NULL,
  detalhes jsonb DEFAULT NULL,
  data_evento timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT auditoria_ibfk_1 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

CREATE INDEX IF NOT EXISTS auditoria_id_usuario_idx ON auditoria (id_usuario);

INSERT INTO localizacao_livro (setor, estante, divisoria, numero) VALUES
('A', '04', '02', 12),
('B', '02', '01', 8),
('C', '01', '03', 21);

INSERT INTO usuarios (nome_usuario, email_usuario, cpf_usuario, tipo_usuario, ativo) VALUES
('Admin LibCore', 'admin@libcore.local', '00000000000', 'ADMIN', true),
('Aluno Teste', 'aluno@libcore.local', '11111111111', 'LEITOR', true);

INSERT INTO livros (etiqueta_rfid, nome_livro, autor_livro, categoria_livro, status_livro, id_localizacao) VALUES
('53:fd:3a:38:63:00:01', 'Livro 1', 'LibCore', 'Teste RFID', 'DISPONIVEL', 1),
('RFID-TEC-1842', 'Engenharia de Software Moderna', 'Autor Teste', 'Tecnologia', 'DISPONIVEL', 1),
('RFID-TEC-2145', 'Banco de Dados', 'Autor Teste', 'Tecnologia', 'DISPONIVEL', 2);

INSERT INTO espacos (nome_espaco, tipo_espaco, capacidade) VALUES
('Sala de estudo 01', 'SALA_ESTUDO', 4),
('Mesa individual 07', 'MESA_INDIVIDUAL', 1),
('Área de leitura', 'AREA_LEITURA', 20);

INSERT INTO salas (id_espaco, nome_sala, status_sala, camera_url, largura_planta, altura_planta, metadata) VALUES
(1, 'Sala de estudo 01', 'ABERTA', NULL, 12.00, 8.00, '{"mapa":"2d","blender_ready":true}'::jsonb);
